# Generated by Django 3.0.2 on 2020-02-29 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200228_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thingtodo',
            old_name='is_deleted',
            new_name='completed',
        ),
        migrations.DeleteModel(
            name='MyList',
        ),
    ]
