# Generated by Django 3.0.2 on 2020-02-29 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200229_1009'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thingtodo',
            options={'verbose_name_plural': 'Things to Do'},
        ),
    ]
