# Generated by Django 3.0.2 on 2020-03-05 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200304_1937'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ThingToDo',
            new_name='Task',
        ),
    ]
