# Generated by Django 3.0.2 on 2020-03-05 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200305_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlist',
            name='things',
        ),
        migrations.AddField(
            model_name='task',
            name='task_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.UserList'),
        ),
        migrations.AddField(
            model_name='userlist',
            name='name',
            field=models.CharField(default='To Do List', max_length=100),
        ),
    ]
