# Generated by Django 3.0.2 on 2020-03-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200305_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_list',
        ),
        migrations.AddField(
            model_name='userlist',
            name='tasks_stored',
            field=models.ManyToManyField(to='app.Task'),
        ),
    ]
