# Generated by Django 3.0.3 on 2020-03-10 18:29

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20200309_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='its_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='list', to='app.UserList'),
        ),
        migrations.AlterField(
            model_name='task',
            name='thing',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
