# Generated by Django 3.0.3 on 2020-03-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20200310_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='thing',
            field=models.CharField(max_length=500),
        ),
    ]
