# Generated by Django 3.0.3 on 2020-03-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20200324_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='creation_date',
        ),
    ]
