# Generated by Django 3.0.3 on 2020-03-24 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0020_task_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='its_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='tasks_listed',
            field=models.ManyToManyField(related_name='tasks_listed', to='app.Task'),
        ),
    ]
